name: Deploy to AWS S3

on:
  push:
    branches:
      - main  # Or your default branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Specify your node version

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build  # Your build script

    - name: Deploy to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: your-s3-bucket-name
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-2'  # Your AWS region
        SOURCE_DIR: 'path_to_your_build_directory'
